# .github/workflows/pages.yml
name: Deploy static site to Pages
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Optional: hier ggf. deine index.html-Aktualisierung laufen lassen
      # - run: node index.html  # falls du den eingebetteten Generator nutzt
      - name: Upload artifact (ALLE Dateien aus dem Repo-Root)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
